// lib/pdf/audit-report.tsx
// Compliance-export PDF for the audit log. Same @react-pdf/renderer
// approach as lib/pdf/renderer.tsx (pure Node, no browser/Chromium).

import React from 'react'
import { Document, Page, View, Text, StyleSheet, renderToBuffer } from '@react-pdf/renderer'

export interface AuditReportRow {
  createdAt:   string
  eventType:   string
  actorName:   string
  actorEmail:  string
  entityType:  string
  entityName:  string
  ipAddress:   string | null
}

export interface AuditReportData {
  agencyName:    string
  workspaceName: string
  generatedBy:   string
  generatedAt:   string
  from:          string
  to:            string
  filters: {
    project?: string
    actor?:   string
    eventType?: string
  }
  totalCount:  number
  truncated:   boolean
  rows:        AuditReportRow[]
}

function fmtDateTime(iso: string) {
  return new Date(iso).toLocaleString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  })
}
function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}

// event_type values look like "sow.sent", "guardian_flag.resolved",
// "security.mfa_enabled" — turn that into readable prose for the report
// without needing a hand-maintained label map for every event the app
// can ever log.
function humanizeEvent(eventType: string): string {
  return eventType
    .split('.')
    .join(' — ')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase())
}

const s = StyleSheet.create({
  page:       { fontFamily: 'Helvetica', fontSize: 9, color: '#1A1A1A', padding: '36 40' },
  header:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2 solid #1A5C3A', paddingBottom: 12, marginBottom: 16 },
  h1:         { fontFamily: 'Helvetica-Bold', fontSize: 15, color: '#1A5C3A', marginBottom: 3 },
  meta:       { fontSize: 8, color: '#909090' },
  metaRight:  { fontSize: 8, color: '#909090', textAlign: 'right' },
  filterBar:  { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 14 },
  filterChip: { fontSize: 7.5, color: '#3D3D3D', backgroundColor: '#F2F0EA', border: '1 solid #E5E1D8', borderRadius: 3, paddingVertical: 3, paddingHorizontal: 7 },
  tableHdr:   { flexDirection: 'row', borderBottom: '1 solid #1A1A1A', paddingBottom: 5, marginBottom: 2 },
  th:         { fontSize: 7, fontFamily: 'Helvetica-Bold', color: '#909090', textTransform: 'uppercase', letterSpacing: 0.4 },
  row:        { flexDirection: 'row', borderBottom: '1 solid #F2F0EA', paddingVertical: 5 },
  td:         { fontSize: 8.5, color: '#1A1A1A' },
  tdSub:      { fontSize: 7.5, color: '#909090' },
  footer:     { position: 'absolute', bottom: 20, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between', paddingTop: 8, borderTop: '1 solid #E5E1D8', fontSize: 7.5, color: '#B0B0B0' },
  pageNum:    { position: 'absolute', bottom: 20, right: 40, fontSize: 7.5, color: '#B0B0B0' },
  truncNote:  { marginTop: 10, fontSize: 8, color: '#B45309', backgroundColor: '#FFFBEB', border: '1 solid #FDE68A', borderRadius: 3, padding: 8 },
})

const COL = { when: 78, event: 150, actor: 130, entity: 'auto' as const }

function AuditReportDocument({ data }: { data: AuditReportData }) {
  const filterChips: string[] = []
  if (data.filters.project)   filterChips.push(`Project: ${data.filters.project}`)
  if (data.filters.actor)     filterChips.push(`User: ${data.filters.actor}`)
  if (data.filters.eventType) filterChips.push(`Event: ${data.filters.eventType}`)

  return (
    <Document>
      <Page size="A4" style={s.page} wrap>
        <View style={s.header} fixed>
          <View>
            <Text style={s.h1}>Audit Log Export</Text>
            <Text style={s.meta}>{data.workspaceName} · {data.agencyName}</Text>
            <Text style={s.meta}>{fmtDate(data.from)} — {fmtDate(data.to)}</Text>
          </View>
          <View>
            <Text style={s.metaRight}>Generated by {data.generatedBy}</Text>
            <Text style={s.metaRight}>{fmtDateTime(data.generatedAt)}</Text>
            <Text style={s.metaRight}>{data.totalCount.toLocaleString()} event{data.totalCount === 1 ? '' : 's'}</Text>
          </View>
        </View>

        {filterChips.length > 0 && (
          <View style={s.filterBar}>
            {filterChips.map((c, i) => <Text key={i} style={s.filterChip}>{c}</Text>)}
          </View>
        )}

        <View style={s.tableHdr} fixed>
          <Text style={[s.th, { width: COL.when }]}>When</Text>
          <Text style={[s.th, { width: COL.event }]}>Event</Text>
          <Text style={[s.th, { width: COL.actor }]}>Actor</Text>
          <Text style={[s.th, { flex: 1 }]}>Record</Text>
        </View>

        {data.rows.map((row, i) => (
          <View key={i} style={s.row} wrap={false}>
            <Text style={[s.td, { width: COL.when }]}>{fmtDateTime(row.createdAt)}</Text>
            <View style={{ width: COL.event }}>
              <Text style={s.td}>{humanizeEvent(row.eventType)}</Text>
            </View>
            <View style={{ width: COL.actor }}>
              <Text style={s.td}>{row.actorName}</Text>
              <Text style={s.tdSub}>{row.actorEmail}</Text>
            </View>
            <View style={{ flex: 1 }}>
              <Text style={s.td}>{row.entityName || '—'}</Text>
              <Text style={s.tdSub}>{row.entityType}{row.ipAddress ? ` · ${row.ipAddress}` : ''}</Text>
            </View>
          </View>
        ))}

        {data.truncated && (
          <Text style={s.truncNote}>
            This PDF shows the first {data.rows.length.toLocaleString()} of {data.totalCount.toLocaleString()} matching events.
            Export CSV for the complete, unabridged record.
          </Text>
        )}

        <View style={s.footer} fixed>
          <Text>ScopeGov compliance export · scopegov.app</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  )
}

export async function renderAuditReportPdf(data: AuditReportData): Promise<Buffer> {
  return renderToBuffer(<AuditReportDocument data={data} />)
}
