// lib/pdf/portfolio-report.tsx
// Compliance/board-facing export of the Portfolio dashboard. Same
// @react-pdf/renderer approach as lib/pdf/audit-report.tsx (pure Node, no
// browser/Chromium) — see the FIX note in api/reports/portfolio/export/
// route.ts for why this exists.

import React from 'react'
import { Document, Page, View, Text, StyleSheet, renderToBuffer } from '@react-pdf/renderer'
import type { PortfolioData } from '@/lib/reports/portfolio-data'
import { PDF_FONT, sanitizeForPdf } from '@/lib/pdf/fonts'

export interface PortfolioReportData {
  agencyName: string
  workspaceName: string
  generatedBy: string
  generatedAt: string
  periodLabel: string
  canViewFinancials: boolean
  data: PortfolioData
}

function fmtDateTime(iso: string) {
  return new Date(iso).toLocaleString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  })
}
function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}
function fmtMoney(amount: number, currency: string): string {
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency', currency, minimumFractionDigits: 0, maximumFractionDigits: 0,
    }).format(amount)
  } catch { return `${currency} ${Math.round(amount).toLocaleString()}` }
}

const s = StyleSheet.create({
  page:       { fontFamily: PDF_FONT.sans, fontSize: 9, color: '#1A1A1A', padding: '36 40' },
  header:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2 solid #1A5C3A', paddingBottom: 12, marginBottom: 16 },
  h1:         { fontFamily: PDF_FONT.bold, fontSize: 15, color: '#1A5C3A', marginBottom: 3 },
  h2:         { fontFamily: PDF_FONT.bold, fontSize: 11, color: '#1A1A1A', marginTop: 18, marginBottom: 8 },
  meta:       { fontSize: 8, color: '#909090' },
  metaRight:  { fontSize: 8, color: '#909090', textAlign: 'right' },
  metricRow:  { flexDirection: 'row', gap: 10, marginBottom: 4 },
  metricBox:  { flex: 1, border: '1 solid #E5E1D8', borderRadius: 3, padding: 8 },
  metricLbl:  { fontSize: 7, color: '#909090', textTransform: 'uppercase', letterSpacing: 0.4, marginBottom: 3 },
  metricVal:  { fontSize: 14, fontFamily: PDF_FONT.bold, color: '#1A1A1A' },
  tableHdr:   { flexDirection: 'row', borderBottom: '1 solid #1A1A1A', paddingBottom: 5, marginBottom: 2 },
  th:         { fontSize: 7, fontFamily: PDF_FONT.bold, color: '#909090', textTransform: 'uppercase', letterSpacing: 0.4 },
  row:        { flexDirection: 'row', borderBottom: '1 solid #F2F0EA', paddingVertical: 5 },
  td:         { fontSize: 8.5, color: '#1A1A1A' },
  tdSub:      { fontSize: 7.5, color: '#909090' },
  emptyNote:  { fontSize: 8.5, color: '#909090', paddingVertical: 8 },
  footer:     { position: 'absolute', bottom: 20, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between', paddingTop: 8, borderTop: '1 solid #E5E1D8', fontSize: 7.5, color: '#B0B0B0' },
})

const FLAG_COL = { project: 130, flag: 210, severity: 55 }
const STALL_COL = { kind: 32, project: 190, since: 90 }

function PortfolioReportDocument({ report }: { report: PortfolioReportData }) {
  const { data, canViewFinancials } = report
  const c = data.current

  const stalledItems = [
    ...data.stalledSows.map(sw => ({ kind: 'SOW', title: sw.projectName, sub: sw.clientName, since: sw.since, amount: null as number | null, currency: null as string | null })),
    ...data.stalledCos.map(co => ({ kind: 'CO', title: `${co.title} — ${co.projectName}`, sub: null as string | null, since: co.since, amount: co.total, currency: co.currency })),
  ].sort((a, b) => new Date(a.since).getTime() - new Date(b.since).getTime())

  return (
    <Document>
      <Page size="A4" style={s.page} wrap>
        <View style={s.header} fixed>
          <View>
            <Text style={s.h1}>Portfolio Report</Text>
            <Text style={s.meta}>{report.workspaceName} · {report.agencyName}</Text>
            <Text style={s.meta}>{report.periodLabel}{c?.snapshotDate ? ` · as of ${fmtDate(c.snapshotDate)}` : ''}</Text>
          </View>
          <View>
            <Text style={s.metaRight}>Generated by {report.generatedBy}</Text>
            <Text style={s.metaRight}>{fmtDateTime(report.generatedAt)}</Text>
          </View>
        </View>

        {c ? (
          <View style={s.metricRow}>
            <View style={s.metricBox}>
              <Text style={s.metricLbl}>Open scope flags</Text>
              <Text style={s.metricVal}>{c.openFlagsCount}</Text>
            </View>
            <View style={s.metricBox}>
              <Text style={s.metricLbl}>Contract value at risk</Text>
              <Text style={s.metricVal}>
                {canViewFinancials && c.contractValueAtRisk !== null ? fmtMoney(c.contractValueAtRisk, data.currency) : '—'}
              </Text>
            </View>
            <View style={s.metricBox}>
              <Text style={s.metricLbl}>Exceptions granted</Text>
              <Text style={s.metricVal}>{c.exceptionsCount}</Text>
            </View>
            <View style={s.metricBox}>
              <Text style={s.metricLbl}>Stalled documents</Text>
              <Text style={s.metricVal}>{c.stalledSowCount + c.stalledCoCount}</Text>
            </View>
          </View>
        ) : (
          <Text style={s.emptyNote}>No scope-health snapshot has run yet for this workspace.</Text>
        )}

        <Text style={s.h2}>Open scope flags ({data.openFlags.length})</Text>
        {data.openFlags.length === 0 ? (
          <Text style={s.emptyNote}>No open flags across the portfolio.</Text>
        ) : (
          <>
            <View style={s.tableHdr} fixed>
              <Text style={[s.th, { width: FLAG_COL.project }]}>Project</Text>
              <Text style={[s.th, { width: FLAG_COL.flag }]}>Flag</Text>
              <Text style={[s.th, { width: FLAG_COL.severity }]}>Severity</Text>
              <Text style={[s.th, { flex: 1 }]}>Raised</Text>
            </View>
            {data.openFlags.map((f, i) => (
              <View key={i} style={s.row} wrap={false}>
                <View style={{ width: FLAG_COL.project }}>
                  <Text style={s.td}>{f.projectName}</Text>
                  {f.clientName && <Text style={s.tdSub}>{f.clientName}</Text>}
                </View>
                <View style={{ width: FLAG_COL.flag }}>
                  <Text style={s.td}>{f.description}</Text>
                  <Text style={s.tdSub}>Ref: {f.sowReference}</Text>
                </View>
                <Text style={[s.td, { width: FLAG_COL.severity, textTransform: 'capitalize' }]}>{f.severity}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={s.td}>{fmtDate(f.createdAt)}</Text>
                  {canViewFinancials && f.contractValue ? (
                    <Text style={s.tdSub}>{fmtMoney(f.contractValue, f.currency)}</Text>
                  ) : null}
                </View>
              </View>
            ))}
          </>
        )}

        <Text style={s.h2}>Stalled documents ({stalledItems.length})</Text>
        {stalledItems.length === 0 ? (
          <Text style={s.emptyNote}>Nothing stalled across the portfolio.</Text>
        ) : (
          <>
            <View style={s.tableHdr} fixed>
              <Text style={[s.th, { width: STALL_COL.kind }]}>Type</Text>
              <Text style={[s.th, { width: STALL_COL.project }]}>Document</Text>
              <Text style={[s.th, { width: STALL_COL.since }]}>Since</Text>
              <Text style={[s.th, { flex: 1 }]}>Amount</Text>
            </View>
            {stalledItems.map((item, i) => (
              <View key={i} style={s.row} wrap={false}>
                <Text style={[s.td, { width: STALL_COL.kind }]}>{item.kind}</Text>
                <View style={{ width: STALL_COL.project }}>
                  <Text style={s.td}>{item.title}</Text>
                  {item.sub && <Text style={s.tdSub}>{item.sub}</Text>}
                </View>
                <Text style={[s.td, { width: STALL_COL.since }]}>{fmtDate(item.since)}</Text>
                <Text style={[s.td, { flex: 1 }]}>
                  {canViewFinancials && item.amount ? fmtMoney(item.amount, item.currency || 'USD') : '—'}
                </Text>
              </View>
            ))}
          </>
        )}

        {c && (
          <>
            <Text style={s.h2}>Exceptions granted, all-time</Text>
            <Text style={s.td}>
              {c.exceptionsCount} scope item{c.exceptionsCount === 1 ? '' : 's'} waived across the portfolio
              {canViewFinancials && c.exceptionsValueTotal !== null
                ? ` — representing ${fmtMoney(c.exceptionsValueTotal, data.currency)} in scope given away outside a change order.`
                : '.'}
            </Text>
          </>
        )}

        <View style={s.footer} fixed>
          <Text>ScopeGov portfolio report · scopegov.app</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  )
}

export async function renderPortfolioReportPdf(report: PortfolioReportData): Promise<Buffer> {
  return renderToBuffer(<PortfolioReportDocument report={sanitizeForPdf(report)} />)
}
