// lib/pdf/reports-report.tsx
//
// FEATURE (deep audit, Reports & Audit re-pass): the Reports page (Scope
// protection + Financial overview — app/(app)/reports/page.tsx,
// api/reports/route.ts) had no export at all. Every other rollup surface
// in the product got this treatment in a prior audit round — the audit
// log (api/reports/audit-export) and the Portfolio dashboard
// (api/reports/portfolio/export) both offer CSV and PDF — but the actual
// contract-value / scope-governance numbers an agency principal would
// most want to hand to a partner or client had no path out of the
// browser. Same @react-pdf/renderer approach, same visual language as
// lib/pdf/audit-report.tsx and lib/pdf/portfolio-report.tsx.

import React from 'react'
import { Document, Page, View, Text, StyleSheet, renderToBuffer } from '@react-pdf/renderer'
import { PDF_FONT, sanitizeForPdf } from '@/lib/pdf/fonts'

function fmtDateTime(iso: string) {
  return new Date(iso).toLocaleString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  })
}
function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}
function fmtMoney(amount: number | null | undefined, currency: string): string {
  if (amount === null || amount === undefined) return '—'
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency', currency, minimumFractionDigits: 0, maximumFractionDigits: 0,
    }).format(amount)
  } catch { return `${currency} ${Math.round(amount).toLocaleString()}` }
}

const s = StyleSheet.create({
  page:       { fontFamily: PDF_FONT.sans, fontSize: 9, color: '#1A1A1A', padding: '36 40' },
  header:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2 solid #1A5C3A', paddingBottom: 12, marginBottom: 16 },
  h1:         { fontFamily: PDF_FONT.bold, fontSize: 15, color: '#1A5C3A', marginBottom: 3 },
  h2:         { fontFamily: PDF_FONT.bold, fontSize: 11, color: '#1A1A1A', marginTop: 18, marginBottom: 8 },
  meta:       { fontSize: 8, color: '#909090' },
  metaRight:  { fontSize: 8, color: '#909090', textAlign: 'right' },
  metricRow:  { flexDirection: 'row', gap: 10, marginBottom: 4 },
  metricBox:  { flex: 1, border: '1 solid #E5E1D8', borderRadius: 3, padding: 8 },
  metricLbl:  { fontSize: 7, color: '#909090', textTransform: 'uppercase', letterSpacing: 0.4, marginBottom: 3 },
  metricVal:  { fontSize: 14, fontFamily: PDF_FONT.bold, color: '#1A1A1A' },
  tableHdr:   { flexDirection: 'row', borderBottom: '1 solid #1A1A1A', paddingBottom: 5, marginBottom: 2 },
  th:         { fontSize: 7, fontFamily: PDF_FONT.bold, color: '#909090', textTransform: 'uppercase', letterSpacing: 0.4 },
  row:        { flexDirection: 'row', borderBottom: '1 solid #F2F0EA', paddingVertical: 5 },
  td:         { fontSize: 8.5, color: '#1A1A1A' },
  tdSub:      { fontSize: 7.5, color: '#909090' },
  emptyNote:  { fontSize: 8.5, color: '#909090', paddingVertical: 8 },
  mixedNote:  { fontSize: 7.5, color: '#B45309', backgroundColor: '#FFFBEB', border: '1 solid #FDE68A', borderRadius: 3, padding: 6, marginBottom: 10 },
  truncNote:  { fontSize: 7.5, color: '#B45309', backgroundColor: '#FFFBEB', border: '1 solid #FDE68A', borderRadius: 3, padding: 6, marginBottom: 10 },
  footer:     { position: 'absolute', bottom: 20, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between', paddingTop: 8, borderTop: '1 solid #E5E1D8', fontSize: 7.5, color: '#B0B0B0' },
})

interface ReportPdfMeta {
  agencyName: string
  workspaceName: string
  generatedBy: string
  generatedAt: string
  periodLabel: string
}

function Header({ meta, title }: { meta: ReportPdfMeta; title: string }) {
  return (
    <View style={s.header} fixed>
      <View>
        <Text style={s.h1}>{title}</Text>
        <Text style={s.meta}>{meta.workspaceName} · {meta.agencyName}</Text>
        <Text style={s.meta}>{meta.periodLabel}</Text>
      </View>
      <View>
        <Text style={s.metaRight}>Generated by {meta.generatedBy}</Text>
        <Text style={s.metaRight}>{fmtDateTime(meta.generatedAt)}</Text>
      </View>
    </View>
  )
}

function Footer() {
  return (
    <View style={s.footer} fixed>
      <Text>ScopeGov reports export · scopegov.app</Text>
      <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  )
}

function MixedCurrencyNote({ currency, availableCurrencies }: { currency: string; availableCurrencies: string[] }) {
  if (availableCurrencies.length <= 1) return null
  return (
    <Text style={s.mixedNote}>
      This workspace has projects in multiple currencies ({availableCurrencies.join(', ')}). Figures below are shown
      in {currency} only — totals are never blended across currencies.
    </Text>
  )
}

// FIX (deep audit, Reports & Audit re-pass — CRITICAL): lib/reports/
// scope-financial-data.ts now caps its queries and reports `truncated`
// when a workspace's data for the selected period exceeds that cap — see
// that file's own comment for why. Surface it here the same way
// MixedCurrencyNote already does, so a PDF handed to someone outside the
// app doesn't imply a completeness this data doesn't have.
function TruncatedNote({ truncated }: { truncated?: boolean }) {
  if (!truncated) return null
  return (
    <Text style={s.truncNote}>
      This report is based on a large volume of data for the selected period and may be undercounting some figures.
      Narrow the date range for a fully accurate total.
    </Text>
  )
}

const FLAG_COL = { project: 220, count: 80 }
const EXC_COL = { deliverable: 200, project: 150 }
const ADJ_COL = { project: 130, change: 170 }

function ScopeReportDocument({ meta, data }: { meta: ReportPdfMeta; data: any }) {
  const { metrics, flagsByProject, exceptionsByProject, adjustments, currency, availableCurrencies, truncated } = data
  return (
    <Document>
      <Page size="A4" style={s.page} wrap>
        <Header meta={meta} title="Scope Protection Report" />
        <MixedCurrencyNote currency={currency} availableCurrencies={availableCurrencies} />
        <TruncatedNote truncated={truncated} />

        <View style={s.metricRow}>
          <View style={s.metricBox}>
            <Text style={s.metricLbl}>Flags raised (confirmed)</Text>
            <Text style={s.metricVal}>{metrics.total_flags ?? 0}</Text>
          </View>
          <View style={s.metricBox}>
            <Text style={s.metricLbl}>Converted to CO (incl. accepted)</Text>
            <Text style={s.metricVal}>{metrics.converted_to_co ?? 0}</Text>
          </View>
          <View style={s.metricBox}>
            <Text style={s.metricLbl}>Recovery rate</Text>
            <Text style={s.metricVal}>
              {metrics.total_flags > 0 ? `${Math.round((metrics.converted_to_co / metrics.total_flags) * 100)}%` : '—'}
            </Text>
          </View>
          <View style={s.metricBox}>
            <Text style={s.metricLbl}>Recovered value</Text>
            <Text style={s.metricVal}>{fmtMoney(metrics.recovered_value, currency)}</Text>
          </View>
        </View>

        <Text style={s.h2}>Flags by project ({(flagsByProject || []).length})</Text>
        {!(flagsByProject || []).length ? (
          <Text style={s.emptyNote}>No scope flags in this period.</Text>
        ) : (
          <>
            <View style={s.tableHdr} fixed>
              <Text style={[s.th, { width: FLAG_COL.project }]}>Project</Text>
              <Text style={[s.th, { width: FLAG_COL.count }]}>Flags</Text>
            </View>
            {flagsByProject.map((p: any) => (
              <View key={p.project_id} style={s.row} wrap={false}>
                <Text style={[s.td, { width: FLAG_COL.project }]}>{p.project_name}</Text>
                <Text style={[s.td, { width: FLAG_COL.count }]}>{p.flag_count}</Text>
              </View>
            ))}
          </>
        )}

        <Text style={s.h2}>Exceptions granted ({(exceptionsByProject || []).length})</Text>
        {!(exceptionsByProject || []).length ? (
          <Text style={s.emptyNote}>No exceptions granted in this period.</Text>
        ) : (
          <>
            <View style={s.tableHdr} fixed>
              <Text style={[s.th, { width: EXC_COL.deliverable }]}>Deliverable</Text>
              <Text style={[s.th, { width: EXC_COL.project }]}>Project</Text>
              <Text style={[s.th, { flex: 1 }]}>Est. value</Text>
            </View>
            {exceptionsByProject.map((e: any) => (
              <View key={e.id} style={s.row} wrap={false}>
                <Text style={[s.td, { width: EXC_COL.deliverable }]}>{e.deliverable}</Text>
                <Text style={[s.td, { width: EXC_COL.project }]}>{e.projects?.name || ''}</Text>
                <Text style={[s.td, { flex: 1 }]}>{fmtMoney(e.estimated_value, currency)}</Text>
              </View>
            ))}
          </>
        )}

        <Text style={s.h2}>Scope adjustments ({(adjustments || []).length})</Text>
        {!(adjustments || []).length ? (
          <Text style={s.emptyNote}>No scope adjustments in this period.</Text>
        ) : (
          <>
            <View style={s.tableHdr} fixed>
              <Text style={[s.th, { width: ADJ_COL.project }]}>Project</Text>
              <Text style={[s.th, { width: ADJ_COL.change }]}>Change</Text>
              <Text style={[s.th, { flex: 1 }]}>Reason</Text>
            </View>
            {adjustments.map((a: any) => (
              <View key={a.id} style={s.row} wrap={false}>
                <Text style={[s.td, { width: ADJ_COL.project }]}>{a.projects?.name || ''}</Text>
                <View style={{ width: ADJ_COL.change }}>
                  <Text style={s.td}>{a.old_value} to {a.new_value}</Text>
                  <Text style={s.tdSub}>{fmtDate(a.adjusted_at)}</Text>
                </View>
                <Text style={[s.td, { flex: 1 }]}>{a.reason}</Text>
              </View>
            ))}
          </>
        )}

        <Footer />
      </Page>
    </Document>
  )
}

const CLIENT_COL = { name: 260 }
const TYPE_COL = { name: 200 }

function FinancialReportDocument({ meta, data }: { meta: ReportPdfMeta; data: any }) {
  const { metrics, byClient, byType, coGrid, currency, availableCurrencies, truncated } = data
  return (
    <Document>
      <Page size="A4" style={s.page} wrap>
        <Header meta={meta} title="Financial Overview Report" />
        <MixedCurrencyNote currency={currency} availableCurrencies={availableCurrencies} />
        <TruncatedNote truncated={truncated} />

        <View style={s.metricRow}>
          <View style={s.metricBox}>
            <Text style={s.metricLbl}>Portfolio contract value</Text>
            <Text style={s.metricVal}>{fmtMoney(metrics.effective_value, currency)}</Text>
          </View>
          <View style={s.metricBox}>
            <Text style={s.metricLbl}>Change-order value in period</Text>
            <Text style={s.metricVal}>{fmtMoney(metrics.co_impact, currency)}</Text>
          </View>
          <View style={s.metricBox}>
            <Text style={s.metricLbl}>COs raised</Text>
            <Text style={s.metricVal}>{metrics.cos_raised ?? 0}</Text>
          </View>
          <View style={s.metricBox}>
            <Text style={s.metricLbl}>CO acceptance rate</Text>
            <Text style={s.metricVal}>
              {metrics.cos_raised > 0 ? `${Math.round((metrics.cos_accepted / metrics.cos_raised) * 100)}%` : '—'}
            </Text>
          </View>
        </View>

        <Text style={s.h2}>Contract value by client ({(byClient || []).length})</Text>
        {!(byClient || []).length ? (
          <Text style={s.emptyNote}>No data in this period.</Text>
        ) : (
          <>
            <View style={s.tableHdr} fixed>
              <Text style={[s.th, { width: CLIENT_COL.name }]}>Client</Text>
              <Text style={[s.th, { flex: 1 }]}>Value</Text>
            </View>
            {byClient.map((c: any) => (
              <View key={c.client_id} style={s.row} wrap={false}>
                <Text style={[s.td, { width: CLIENT_COL.name }]}>{c.client_name}</Text>
                <Text style={[s.td, { flex: 1 }]}>{fmtMoney(c.value, currency)}</Text>
              </View>
            ))}
          </>
        )}

        <Text style={s.h2}>Contract value by project type ({(byType || []).length})</Text>
        {!(byType || []).length ? (
          <Text style={s.emptyNote}>No data in this period.</Text>
        ) : (
          <>
            <View style={s.tableHdr} fixed>
              <Text style={[s.th, { width: TYPE_COL.name }]}>Type</Text>
              <Text style={[s.th, { flex: 1 }]}>Value</Text>
            </View>
            {byType.map((t: any) => (
              <View key={t.type} style={s.row} wrap={false}>
                <Text style={[s.td, { width: TYPE_COL.name }]}>{t.type_label}</Text>
                <Text style={[s.td, { flex: 1 }]}>{fmtMoney(t.value, currency)}</Text>
              </View>
            ))}
          </>
        )}

        {coGrid && (
          <>
            <Text style={s.h2}>Change order impact grid</Text>
            <View style={s.metricRow}>
              <View style={s.metricBox}><Text style={s.metricLbl}>Sent</Text><Text style={s.metricVal}>{coGrid.raised ?? 0}</Text></View>
              <View style={s.metricBox}><Text style={s.metricLbl}>Accepted</Text><Text style={s.metricVal}>{coGrid.accepted ?? 0}</Text></View>
              <View style={s.metricBox}><Text style={s.metricLbl}>Declined</Text><Text style={s.metricVal}>{coGrid.declined ?? 0}</Text></View>
              <View style={s.metricBox}><Text style={s.metricLbl}>Pending</Text><Text style={s.metricVal}>{coGrid.pending ?? 0}</Text></View>
              <View style={s.metricBox}><Text style={s.metricLbl}>Closed / expired</Text><Text style={s.metricVal}>{coGrid.closed ?? 0}</Text></View>
            </View>
          </>
        )}

        <Footer />
      </Page>
    </Document>
  )
}

export async function renderScopeReportPdf(meta: ReportPdfMeta, data: any): Promise<Buffer> {
  return renderToBuffer(<ScopeReportDocument meta={sanitizeForPdf(meta)} data={sanitizeForPdf(data)} />)
}

export async function renderFinancialReportPdf(meta: ReportPdfMeta, data: any): Promise<Buffer> {
  return renderToBuffer(<FinancialReportDocument meta={sanitizeForPdf(meta)} data={sanitizeForPdf(data)} />)
}
