#!/usr/bin/env python3
"""
Regenerates lib/pdf/fonts/noto-sans-data.ts (the PDF renderer's embedded
Unicode font) from the Noto Sans TTFs in the @expo-google-fonts/noto-sans npm
package, subset to Latin / Latin-Extended / Vietnamese / Cyrillic / Greek plus
general punctuation and currency symbols.

Why embedded as base64 instead of read from disk: react-pdf would otherwise
read the .ttf files at render time, which on serverless only works if every
PDF route's file tracing includes them. A TS module is bundled with the code,
so there is nothing to trace and nothing to get wrong per route.

Usage:
  npm pack @expo-google-fonts/noto-sans && tar -xzf expo-google-fonts-noto-sans-*.tgz
  pip install fonttools brotli
  python3 scripts/build-pdf-fonts.py ./package
Font licence: SIL OFL 1.1 (lib/pdf/fonts/OFL-NotoSans.txt).
"""
import base64, subprocess, sys, tempfile, os
from fontTools.ttLib import TTFont

src = sys.argv[1] if len(sys.argv) > 1 else './package'
faces = {
    'REGULAR':     '400Regular/NotoSans_400Regular',
    'BOLD':        '700Bold/NotoSans_700Bold',
    'ITALIC':      '400Regular_Italic/NotoSans_400Regular_Italic',
    'BOLD_ITALIC': '700Bold_Italic/NotoSans_700Bold_Italic',
}
unicodes = ('U+0020-007E,U+00A0-024F,U+02B0-02FF,U+0300-036F,U+0370-03FF,U+0400-052F,U+1E00-1EFF,'
            'U+2000-206F,U+20A0-20CF,U+2100-214F,U+2212,U+2215,U+2260-2265,U+FEFF,U+FFFD')
# NB: the ranges above are only what we ASK pyftsubset to keep — it silently drops
# any code point the source font doesn't have. The sanitizer must not trust them,
# so the code points that actually survive in ALL four faces are computed from
# each subset's cmap below and emitted as NOTO_SANS_SUPPORTED_RANGES.

out = ['// AUTO-GENERATED by scripts/build-pdf-fonts.py — do not edit by hand.',
       '// Noto Sans (SIL OFL 1.1), subset to Latin/Latin-Ext/Vietnamese/Cyrillic/Greek + punctuation & currency.', '']
supported = None
for name, path in faces.items():
    with tempfile.NamedTemporaryFile(suffix='.ttf', delete=False) as tmp:
        tmp_path = tmp.name
    subprocess.check_call(['pyftsubset', f'{src}/{path}.ttf', f'--unicodes={unicodes}',
                           '--layout-features=kern,liga,mark,mkmk', '--no-hinting', '--desubroutinize',
                           f'--output-file={tmp_path}'])
    b64 = base64.b64encode(open(tmp_path, 'rb').read()).decode()
    cps = set(TTFont(tmp_path).getBestCmap().keys())
    supported = cps if supported is None else (supported & cps)
    os.unlink(tmp_path)
    out.append(f"export const NOTO_SANS_{name}_B64 = '{b64}'")
ranges = []
for cp in sorted(supported):
    if ranges and cp == ranges[-1][1] + 1:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp])
out.append('// Code points present in ALL four faces (from each subset\'s cmap) — what the sanitizer allows.')
out.append('export const NOTO_SANS_SUPPORTED_RANGES: Array<[number, number]> = ' + '[' + ', '.join(f'[{a}, {b}]' for a, b in ranges) + ']')
open('lib/pdf/fonts/noto-sans-data.ts', 'w').write('\n'.join(out) + '\n')
print('wrote lib/pdf/fonts/noto-sans-data.ts')
